In [ ]:
import random
import numpy as np
from numpy.linalg import eig

In [ ]:
N = 1000

In [ ]:
arr = np.random.randn(N,N)

In [ ]:
eig_val,eig_vec = eig((arr + arr.T)/2)

In [ ]:
eig_val

In [ ]:
eig_vec

array([[-0.00488141,  0.02244233, -0.01069324, ...,  0.00331009,
         0.00624372,  0.00167242],
       [-0.10063271, -0.05232952,  0.02641847, ..., -0.00474474,
         0.02902054, -0.02764489],
       [ 0.05125933,  0.0396581 , -0.02986975, ...,  0.01007926,
         0.03241887,  0.01350811],
       ...,
       [ 0.00134349, -0.0027411 ,  0.00981263, ...,  0.02357582,
         0.01432836, -0.01630122],
       [-0.03042359, -0.01911403,  0.0363121 , ...,  0.00124184,
        -0.00856221, -0.01958364],
       [-0.01172441,  0.04571446, -0.01625894, ...,  0.03743554,
        -0.00086575, -0.00024015]])

In [ ]:
eig_vec.shape

(1000, 1000)

In [ ]:
temp = eig_vec @ np.diag(abs(np.random.randn(N))) @ eig_vec.T

In [ ]:
A = temp @ temp.T

In [ ]:
A

array([[ 1.01380697,  0.05981665,  0.06383368, ...,  0.0796321 ,
        -0.05609313,  0.06722991],
       [ 0.05981665,  1.0386612 ,  0.01332081, ...,  0.08223583,
        -0.01120709, -0.01340456],
       [ 0.06383368,  0.01332081,  1.07560533, ...,  0.10168627,
        -0.00505666, -0.03805923],
       ...,
       [ 0.0796321 ,  0.08223583,  0.10168627, ...,  1.0379901 ,
         0.06401327, -0.04838804],
       [-0.05609313, -0.01120709, -0.00505666, ...,  0.06401327,
         1.03481095, -0.01074535],
       [ 0.06722991, -0.01340456, -0.03805923, ..., -0.04838804,
        -0.01074535,  1.08606321]])

In [ ]:
A.shape

(1000, 1000)

In [ ]:
sigma = np.linalg.inv(A)

In [ ]:
sigma

array([[ 3587.37547903,  -353.92435334,  -450.48280743, ...,
         1714.53203335,  1408.77767604,   805.33998386],
       [ -353.92435332,  2263.01460768,  -324.40044022, ...,
          879.28334398,  -164.76297523,  2205.47898664],
       [ -450.48280743,  -324.40044022,  1034.57443305, ...,
          136.72420216,  -755.8533021 , -1170.80886405],
       ...,
       [ 1714.53203336,   879.28334397,   136.72420215, ...,
         2002.96064685,   244.6497213 ,  1098.10166392],
       [ 1408.77767604,  -164.76297524,  -755.8533021 , ...,
          244.64972129,  1556.04152005,  1541.28350407],
       [  805.33998387,  2205.47898663, -1170.80886406, ...,
         1098.10166392,  1541.28350408,  4640.86288463]])

In [ ]:
sigma.T

array([[ 3587.37547903,  -353.92435332,  -450.48280743, ...,
         1714.53203336,  1408.77767604,   805.33998387],
       [ -353.92435334,  2263.01460768,  -324.40044022, ...,
          879.28334397,  -164.76297524,  2205.47898663],
       [ -450.48280743,  -324.40044022,  1034.57443305, ...,
          136.72420215,  -755.8533021 , -1170.80886406],
       ...,
       [ 1714.53203335,   879.28334398,   136.72420216, ...,
         2002.96064685,   244.64972129,  1098.10166392],
       [ 1408.77767604,  -164.76297523,  -755.8533021 , ...,
          244.6497213 ,  1556.04152005,  1541.28350408],
       [  805.33998386,  2205.47898664, -1170.80886405, ...,
         1098.10166392,  1541.28350407,  4640.86288463]])

In [ ]:
X0 = np.zeros(N)

In [ ]:
X0[:5]

array([0., 0., 0., 0., 0.])

In [ ]:
import math

In [ ]:
def normal(mean,var):
    return mean +  math.sqrt(var) * float(np.random.randn(1))

In [ ]:
x = np.zeros((N,N))

In [ ]:
for i in range(N):
    temp = np.delete(X0,[i],None)
    var = 1/A[i][i]
    intermediate = (np.delete(A[i],[i],None)/(-A[i][i]))
    mean = intermediate @ temp.T
    X0[i] = normal(mean,var)
    x[i] = X0

In [ ]:
x

array([[ 1.54596136,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.54596136, -0.23473708,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.54596136, -0.23473708, -0.60060181, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.54596136, -0.23473708, -0.60060181, ..., -1.57313057,
         0.        ,  0.        ],
       [ 1.54596136, -0.23473708, -0.60060181, ..., -1.57313057,
         0.00941101,  0.        ],
       [ 1.54596136, -0.23473708, -0.60060181, ..., -1.57313057,
         0.00941101,  1.46734522]])

In [ ]:
sum = (np.outer(x[0],x[0].T))/N
for i in range(1,N):
    sum = sum  + (np.outer(x[i],x[i].T))/N

In [ ]:
sum

array([[ 2.38999652e+00, -3.62531555e-01, -9.26650182e-01, ...,
        -7.29599720e-03,  2.90981091e-05,  2.26845901e-03],
       [-3.62531555e-01,  5.50463937e-02,  1.40701547e-01, ...,
         1.10781621e-03, -4.41822497e-06, -3.44440328e-04],
       [-9.26650182e-01,  1.40701547e-01,  3.60001094e-01, ...,
         2.83447521e-03, -1.13045368e-05, -8.81290202e-04],
       ...,
       [-7.29599720e-03,  1.10781621e-03,  2.83447521e-03, ...,
         7.42421933e-03, -2.96094884e-05, -2.30832562e-03],
       [ 2.90981091e-05, -4.41822497e-06, -1.13045368e-05, ...,
        -2.96094884e-05,  1.77134140e-07,  1.38091975e-05],
       [ 2.26845901e-03, -3.44440328e-04, -8.81290202e-04, ...,
        -2.30832562e-03,  1.38091975e-05,  2.15310200e-03]])

In [ ]:
sigma

array([[ 3587.37547903,  -353.92435334,  -450.48280743, ...,
         1714.53203335,  1408.77767604,   805.33998386],
       [ -353.92435332,  2263.01460768,  -324.40044022, ...,
          879.28334398,  -164.76297523,  2205.47898664],
       [ -450.48280743,  -324.40044022,  1034.57443305, ...,
          136.72420216,  -755.8533021 , -1170.80886405],
       ...,
       [ 1714.53203336,   879.28334397,   136.72420215, ...,
         2002.96064685,   244.6497213 ,  1098.10166392],
       [ 1408.77767604,  -164.76297524,  -755.8533021 , ...,
          244.64972129,  1556.04152005,  1541.28350407],
       [  805.33998387,  2205.47898663, -1170.80886406, ...,
         1098.10166392,  1541.28350408,  4640.86288463]])

In [ ]:
dist = np.linalg.norm(sum-sigma)

In [ ]:
dist

1302469.976640898